BEGIN;

ALTER TABLE services
ALTER COLUMN price DROP NOT NULL;

ALTER TABLE services
ALTER COLUMN duration DROP NOT NULL;

ALTER TABLE services
ALTER COLUMN appointment_time DROP NOT NULL;

ALTER TABLE services
ALTER COLUMN lng DROP NOT NULL;

ALTER TABLE services
ALTER COLUMN lat DROP NOT NULL;

COMMIT;
