schemes:
- http
- https
swagger: "2.0"
info:
  title: DarkPanda backend API service
  contact:
    name: Chi-Han Huang
    email: huangchiheng@gmail.com
  version: 0.0.1
host: localhost:3333
basePath: /api/v1
paths:
  /auth/revoke-jwt:
    post:
      security:
      - Bearer: []
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      produces:
      - application/json
      tags:
      - auth
      responses:
        "200":
          description: Revoke the jwt token to logout the user
          schema:
            type: object
  /auth/send-verify-code:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      produces:
      - application/json
      tags:
      - auth
      parameters:
      - name: body
        in: body
        schema:
          type: object
          required:
          - uuid
          properties:
            uuid:
              type: string
      responses:
        "200":
          description: send SMS verify code to login
          schema:
            type: object
            properties:
              mobile:
                type: string
              uuid:
                type: string
              verify_prefix:
                type: string
  /auth/verify-code:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      produces:
      - application/json
      tags:
      - auth
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            mobile:
              type: string
            uuid:
              type: string
            verify_char:
              type: string
            verify_dig:
              type: string
      responses:
        "200":
          description: verify SMS code response
          schema:
            type: object
            properties:
              jwt:
                type: string
  /chat:
    post:
      security:
      - Bearer: []
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      produces:
      - application/json
      tags:
      - chat
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            avatar_url:
              type: string
            channel_uuid:
              type: string
            created_at:
              type: string
            expired_at:
              type: string
            inquiry_uuid:
              type: string
            latest_message:
              type: array
              items:
                type: object
                properties:
                  content:
                    type: string
                  created_at:
                    type: string
                  from:
                    type: string
                  to:
                    type: string
                  type:
                    type: string
                    enum:
                    - text
                    - service_detail
                    - confirmed_service
            service_type:
              type: string
              enum:
              - inquiring
              - canceled
              - expired
              - booked
              - chatting
              - wait_for_inquirer_approve
            username:
              type: string
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
tags:
- name: auth
- name: chat
