// Code generated by sqlc. DO NOT EDIT.
// source: inquiry.sql

package models

import (
	"context"
	"database/sql"
)

const getInquiryByInquirerID = `-- name: GetInquiryByInquirerID :one
SELECT id, inquirer_id, budget, service_type, inquiry_status, created_at, updated_at, deleted_at FROM service_inquiries
WHERE inquirer_id = $1
AND inquiry_status = $2
`

type GetInquiryByInquirerIDParams struct {
	InquirerID    sql.NullInt32 `json:"inquirer_id"`
	InquiryStatus InquiryStatus `json:"inquiry_status"`
}

func (q *Queries) GetInquiryByInquirerID(ctx context.Context, arg GetInquiryByInquirerIDParams) (ServiceInquiry, error) {
	row := q.queryRow(ctx, q.getInquiryByInquirerIDStmt, getInquiryByInquirerID, arg.InquirerID, arg.InquiryStatus)
	var i ServiceInquiry
	err := row.Scan(
		&i.ID,
		&i.InquirerID,
		&i.Budget,
		&i.ServiceType,
		&i.InquiryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
