// Code generated by sqlc. DO NOT EDIT.
// source: chatrooms.sql

package models

import (
	"context"
	"database/sql"
)

const createChatroom = `-- name: CreateChatroom :one
INSERT INTO chatrooms(
    inquiry_id,
    channel_uuid,
    message_count
) VALUES ($1, $2, $3)
RETURNING id, inquiry_id, channel_uuid, message_count, created_at, expired_at, updated_at, deleted_at, chatroom_type
`

type CreateChatroomParams struct {
	InquiryID    int32          `json:"inquiry_id"`
	ChannelUuid  sql.NullString `json:"channel_uuid"`
	MessageCount sql.NullInt32  `json:"message_count"`
}

func (q *Queries) CreateChatroom(ctx context.Context, arg CreateChatroomParams) (Chatroom, error) {
	row := q.queryRow(ctx, q.createChatroomStmt, createChatroom, arg.InquiryID, arg.ChannelUuid, arg.MessageCount)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.InquiryID,
		&i.ChannelUuid,
		&i.MessageCount,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ChatroomType,
	)
	return i, err
}
