// Code generated by sqlc. DO NOT EDIT.
// source: payments.sql

package models

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
	payer_id,
	service_id,
	price
) VALUES ($1, $2, $3)
RETURNING id, payer_id, service_id, price, created_at, updated_at, deleted_at, refunded
`

type CreatePaymentParams struct {
	PayerID   int32  `json:"payer_id"`
	ServiceID int32  `json:"service_id"`
	Price     string `json:"price"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.queryRow(ctx, q.createPaymentStmt, createPayment, arg.PayerID, arg.ServiceID, arg.Price)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.ServiceID,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Refunded,
	)
	return i, err
}
