// Code generated by entc, DO NOT EDIT.

package groupusers

import (
	"fmt"
)

const (
	// Label holds the string label denoting the groupusers type in the database.
	Label = "group_users"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuthType holds the string denoting the auth_type field in the database.
	FieldAuthType = "auth_type"

	// Table holds the table name of the groupusers in the database.
	Table = "group_users"
)

// Columns holds all SQL columns for groupusers fields.
var Columns = []string{
	FieldID,
	FieldAuthType,
}

// AuthType defines the type for the auth_type enum field.
type AuthType string

// AuthType values.
const (
	AuthTypeAdmin AuthType = "admin"
	AuthTypeUser  AuthType = "user"
)

func (at AuthType) String() string {
	return string(at)
}

// AuthTypeValidator is a validator for the "auth_type" field enum values. It is called by the builders before save.
func AuthTypeValidator(at AuthType) error {
	switch at {
	case AuthTypeAdmin, AuthTypeUser:
		return nil
	default:
		return fmt.Errorf("groupusers: invalid enum value for auth_type field: %q", at)
	}
}
