// Code generated by go-swagger; DO NOT EDIT.

// Package restapi DarkPanda backend API service
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//  Contact: Chi-Han Huang<huangchiheng@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/plain
//
// swagger:meta
package restapi
