// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "DarkPanda backend API service",
    "contact": {
      "name": "Chi-Han Huang",
      "email": "huangchiheng@gmail.com"
    },
    "version": "0.0.1"
  },
  "paths": {
    "/hello": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "DarkPanda backend API service",
    "contact": {
      "name": "Chi-Han Huang",
      "email": "huangchiheng@gmail.com"
    },
    "version": "0.0.1"
  },
  "paths": {
    "/hello": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  }
}`))
}
