// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/huangc28/go-darkpanda-backend/ent/schema"
	"github.com/huangc28/go-darkpanda-backend/ent/service"
	"github.com/huangc28/go-darkpanda-backend/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	serviceFields := schema.Service{}.Fields()
	_ = serviceFields
	// serviceDescGirlReady is the schema descriptor for girl_ready field.
	serviceDescGirlReady := serviceFields[8].Descriptor()
	// service.DefaultGirlReady holds the default value on creation for the girl_ready field.
	service.DefaultGirlReady = serviceDescGirlReady.Default.(bool)
	// serviceDescManReady is the schema descriptor for man_ready field.
	serviceDescManReady := serviceFields[9].Descriptor()
	// service.DefaultManReady holds the default value on creation for the man_ready field.
	service.DefaultManReady = serviceDescManReady.Default.(bool)
	// serviceDescCreatedAt is the schema descriptor for created_at field.
	serviceDescCreatedAt := serviceFields[10].Descriptor()
	// service.DefaultCreatedAt holds the default value on creation for the created_at field.
	service.DefaultCreatedAt = serviceDescCreatedAt.Default.(func() time.Time)
	// serviceDescUpdatedAt is the schema descriptor for updated_at field.
	serviceDescUpdatedAt := serviceFields[11].Descriptor()
	// service.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	service.DefaultUpdatedAt = serviceDescUpdatedAt.Default.(func() time.Time)
	// service.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	service.UpdateDefaultUpdatedAt = serviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPhoneVerified is the schema descriptor for phone_verified field.
	userDescPhoneVerified := userFields[1].Descriptor()
	// user.DefaultPhoneVerified holds the default value on creation for the phone_verified field.
	user.DefaultPhoneVerified = userDescPhoneVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
