// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupUsers is the predicate function for groupusers builders.
type GroupUsers func(*sql.Selector)

// Inquiry is the predicate function for inquiry builders.
type Inquiry func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRefCodes is the predicate function for userrefcodes builders.
type UserRefCodes func(*sql.Selector)
